<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\Maker;
use App\Models\CarModel;
use Illuminate\Support\Arr;

class CarTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $makerName = Maker::pluck('name')->toArray();
        $carNameArr = CarModel::pluck('name')->toArray();
        $nameArray = explode("　", Arr::random($carNameArr));
        $data = [];
        for ($i = 1; $i <= 100; $i++) {
            $cars = [
                'id' => $i,
                'customer_id' => rand(1, 10),
                'public_status_code' => 101,
                'published_date' => Carbon::now(),
                'is_in_transaction' => 0,
                'is_in_contract' => 0,
                'is_car_delivery_complete' => 0,
                'is_trading_complete' => 0,
                'trading_no' => strtoupper(Str::random(5)) . $i,
                'dealer_introduction_code' => null,
                'trading_memo' => null,
                'buyer_id' => null,
                'total_vehicle_price' => null,
                'is_coating' => null,
                'coating_fee' => null,
                'is_film' => null,
                'film_fee' => null,
                'is_warranty_inheritance' => null,
                'warranty_inheritance_fee' => null,
                'is_electric_components' => null,
                'electric_components_fee' => null,
                'is_shift_gate_warranty' => null,
                'shift_gate_warranty_fee' => null,
                'is_other' => null,
                'other_fee' => null,
                'transport_fee' => null,
                'acquisition_tax' => null,
                'payment_methods' => null,
                'seller_signature' => null,
                'buyer_signature' => null,
                'create_id' => null,
                'create_date' => null,
                'maker_name' => Arr::random($makerName),
                'car_name' => implode("　", array_slice($nameArray, 1)),
                'grade_name' => null,
                'model_num' => null,
                'category_num' => null,
                'car_num' => null,
                'first_registration_date' => null,
                'inspection_date' => null,
                'model_official' => null,
                'chassis_num' => null,
                'engine_model' => null,
                'camera_around_view_code' => null,
                'sell_time' => "sell time",
                'door_count' => null,
                'seating_capacity' => null,
                'steering_place_code' => null,
                'engine_place_code' => null,
                'engine_fuel_code' => null,
                'engine_displacement' => null,
                'drive_shaft_code' => null,
                'transmission_type_code' => null,
                'transmission_place_code' => null,
                'transmission_count_code' => null,
                'max_load' => null,
                'recycle_ticket_code' => null,
                'recycle_price' => null,
                'recycle_no' => null,
                'recycle_airbag_price' => null,
                'recycle_freon_price' => null,
                'recycle_shredder_price' => null,
                'recycle_information_management_price' => null,
                'meter_condition_code' => null,
                'meter_record_note_code' => null,
                'warranty_code' => null,
                'record_note_code' => null,
                'instruction_car_code' => null,
                'instruction_audio_code' => null,
                'instruction_navi_code' => null,
                'instruction_other_code' => null,
                'leather_seat_code' => null,
                'tv_code' => null,
                'navi_code' => null,
                'camera_front_code' => null,
                'camera_side_code' => null,
                'camera_rear_code' => null,
                'spare_key' => null,
                'etc_code' => null,
                'sunroof_code' => null,
                'aluminum_wheel_code' => null,
                'wheel_size_code' => null,
                'tire_code' => null,
                'tire_groove_front_right' => null,
                'tire_groove_front_left' => null,
                'tire_groove_rear_right' => null,
                'tire_groove_rear_left' => null,
                'color_name_code' => null,
                'color_name' => null,
                'color_category_code' => null,
                'color_interior_code' => null,
                'color_original_code' => null,
                'mileage' => null,
                'smell_tobacco_code' => null,
                'smell_pet_code' => null,
                'smell_other_code' => null,
                'damage_dashboard_code' => null,
                'damage_steering_code' => null,
                'damage_seat_code' => null,
                'damage_roof_code' => null,
                'repair_history_code' => null,
                'repair_code' => null,
                'repair_note' => null,
                'model_year' => rand(2010, 2020),
                'total_price' => null,
                'system_usage_fee' => null,
                'income_price' => null,
                'sell_time_code' => null,
                'image1' => null,
                'image2' => null,
                'image3' => null,
                'image4' => null,
                'image5' => null,
                'image6' => null,
                'image7' => null,
                'image8' => null,
                'image9' => null,
                'image10' => null,
                'image11' => null,
                'image12' => null,
                'image13' => null,
                'image14' => null,
                'image15' => null,
                'image16' => null,
                'image17' => null,
                'image18' => null,
                'image19' => null,
                'image20' => null,
                'image21' => null,
                'image22' => null,
                'image23' => null,
                'image24' => null,
                'image25' => null,
                'development_image' => null,
                'inspection_image' => null,
                'liability_insurance_image' => null,
                'value_total_code' => null,
                'value_exterior_code' => null,
                'value_interior_code' => null,
                'quick_price' => null,
                'quick_price_from' => null,
                'quick_price_to' => null,
                'length' => null,
                'width' => null,
                'height' => null,
                'weight' => null,
                'total_weight' => null,
                'axile_weight_f_f' => null,
                'axile_weight_f_r' => null,
                'axile_weight_r_f' => null,
                'axile_weight_r_r' => null,
                'theft_date' => null,
                'mortgage' => null,
                'seller_introduction_code' => null,
                'buyer_introduction_code' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ];
            array_push($data, $cars);
        }

        if (DB::table('cars')->count() == 0) {
            DB::table('cars')->insert($data);
        }
    }
}
